#include "Program.h"

#include "Identifier.h"
#include "Body.h"

#include <Managers/CodeManager.h>

#include <Parser/Class/ClassDefinition.h>

#include <Parser/Expressions/Integer.h>
#include <Parser/VariableDeclaration.h>
#include <Parser/ArrayVariableType.h>
#include <Parser/VariableType.h>

using namespace Parser;

Program::Program(Identifier* p_ID, Body* p_Body) :
	m_ID(p_ID),
	m_Body(p_Body)
{
}

void Program::Generate()
{
	GenerateHeader();
	GenerateClassDefinitions();
	GenerateStaticVariables();
	GenerateMethods();
	GenerateClassBodies();
	GenerateMain();
}

void Program::GenerateHeader()
{
	// Write the disclaimer.
	Managers::CodeManager::Writer()->WriteLnInd("// Code generated by ObjSubpclTranspiler2 - DO NOT EDIT");
	Managers::CodeManager::Writer()->WriteLnInd("// Remember to compile with -fms-extensions");
	Managers::CodeManager::Writer()->WriteLn();

	// Write our includes.
	Managers::CodeManager::Writer()->WriteLnInd("#include <stdio.h>");
	Managers::CodeManager::Writer()->WriteLnInd("#include <string.h>");
	Managers::CodeManager::Writer()->WriteLn();
}

void Program::GenerateClassDefinitions()
{
	if (!m_Body->m_Classes)
		return;

	for (auto s_Class : *m_Body->m_Classes)
		s_Class->GenerateDefinitions();
}

void Program::GenerateStaticVariables()
{
	if (!m_Body->m_Variables)
		return;

	for (auto s_Variable : *m_Body->m_Variables)
	{
		for (auto s_ID : *s_Variable->m_IDs)
		{
			Managers::CodeManager::Writer()->WriteInd("static " + s_Variable->m_Type->ToString() + " " + s_ID->m_Name);

			// If this is an array then add the element count after the variable name.
			if (s_Variable->m_Type->m_Type == VariableTypes::Array)
			{
				auto s_Type = (ArrayVariableType*)s_Variable->m_Type;
				Managers::CodeManager::Writer()->Write("[");
				Managers::CodeManager::Writer()->Write(s_Type->m_ElementCount->m_Value);
				Managers::CodeManager::Writer()->Write("]");
			}

			Managers::CodeManager::Writer()->WriteLn(";");
		}
	}

	Managers::CodeManager::Writer()->WriteLn();
}

void Program::GenerateMethods()
{
	if (!m_Body->m_Procedures)
		return;

	// TODO: Write methods.
	Managers::CodeManager::Writer()->WriteLn();
}

void Program::GenerateClassBodies()
{
	if (!m_Body->m_Classes)
		return;

	for (auto s_Class : *m_Body->m_Classes)
		s_Class->GenerateBody();
}

void Program::GenerateMain()
{
	Managers::CodeManager::Writer()->WriteLnInd("void main()");
	Managers::CodeManager::Writer()->WriteLnInd("{");

	// TODO: Write main body statements.

	Managers::CodeManager::Writer()->WriteLnInd("}");
	Managers::CodeManager::Writer()->WriteLn();
}
